///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0bc3d6e8-563a-4ef8-83ae-f710cc93f1c5")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.RakutenKdreamsAppFolder _rakutenkdreams;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("0bc3d6e8-563a-4ef8-83ae-f710cc93f1c5")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "0bc3d6e8-563a-4ef8-83ae-f710cc93f1c5", ".\\RepositoryImages\\MyTestRepository0bc3d6e8.rximgres")
        {
            _rakutenkdreams = new MyTestRepositoryFolders.RakutenKdreamsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0bc3d6e8-563a-4ef8-83ae-f710cc93f1c5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RakutenKdreams folder.
        /// </summary>
        [RepositoryFolder("81f7f6b6-051b-47bc-9c43-c66c557c9dfa")]
        public virtual MyTestRepositoryFolders.RakutenKdreamsAppFolder RakutenKdreams
        {
            get { return _rakutenkdreams; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The RakutenKdreamsAppFolder folder.
        /// </summary>
        [RepositoryFolder("81f7f6b6-051b-47bc-9c43-c66c557c9dfa")]
        public partial class RakutenKdreamsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _lblログイン中Info;
            RepoItemInfo _btnloginInfo;

            /// <summary>
            /// Creates a new RakutenKdreams  folder.
            /// </summary>
            public RakutenKdreamsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RakutenKdreams", "/dom[@domain='t.keirin.kdreams.jp']", parentFolder, 30000, null, false, "81f7f6b6-051b-47bc-9c43-c66c557c9dfa", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "TxtUsername", ".//form[@id='JS_FORM_LOGIN']//input[@name='userid']", "element", 30000, null, "8096ae46-c355-4dc0-94fa-a09d2e16b858");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//input[@name='password']", "element", 30000, null, "b4a2258f-8f2b-4b86-b35d-c9e8fcb99820");
                _lblログイン中Info = new RepoItemInfo(this, "Lblログイン中", "html//div[@id='MAIN']//div[@class='member_section']/p[@class='message']", ".//div[#'MAIN']//p[@innertext='ログイン中']", 30000, null, "d46def42-8621-40e9-a8db-06673450df18");
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//p[#'JS_GO_LOGIN']", "element", 30000, null, "536f1184-a9ff-47c8-b1c8-5480d85a7709");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("81f7f6b6-051b-47bc-9c43-c66c557c9dfa")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("81f7f6b6-051b-47bc-9c43-c66c557c9dfa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtUsername item.
            /// </summary>
            [RepositoryItem("8096ae46-c355-4dc0-94fa-a09d2e16b858")]
            public virtual Ranorex.InputTag TxtUsername
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUsername item info.
            /// </summary>
            [RepositoryItemInfo("8096ae46-c355-4dc0-94fa-a09d2e16b858")]
            public virtual RepoItemInfo TxtUsernameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("b4a2258f-8f2b-4b86-b35d-c9e8fcb99820")]
            public virtual Ranorex.InputTag TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("b4a2258f-8f2b-4b86-b35d-c9e8fcb99820")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The Lblログイン中 item.
            /// </summary>
            [RepositoryItem("d46def42-8621-40e9-a8db-06673450df18")]
            public virtual Ranorex.PTag Lblログイン中
            {
                get
                {
                    return _lblログイン中Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Lblログイン中 item info.
            /// </summary>
            [RepositoryItemInfo("d46def42-8621-40e9-a8db-06673450df18")]
            public virtual RepoItemInfo Lblログイン中Info
            {
                get
                {
                    return _lblログイン中Info;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("536f1184-a9ff-47c8-b1c8-5480d85a7709")]
            public virtual Ranorex.PTag BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("536f1184-a9ff-47c8-b1c8-5480d85a7709")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
